-- Simple COSIRA forms status table (following Japan pattern)
CREATE OR REPLACE TABLE COSIRA_FORMS_STATUS (
    FORM_ID NUMBER(38,0),
    FORM_KEY VARCHAR(100),
    FORM_NAME VARCHAR(500),
    FORM_TYPE VARCHAR(100),
    RECORD_COUNT NUMBER(38,0) DEFAULT 0,
    STATUS VARCHAR(100), -- PENDING, COMPLETED, FAILED
    LAST_EXTRACTED TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE VARCHAR(1000)
) COMMENT = 'Tracks COSIRA form extraction status - following Japan DAG pattern';